// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptInviteReducer from "../accept_invite_reducer";
import AddInventoryItemReducer from "../add_inventory_item_reducer";
import CreateDeadlineReducer from "../create_deadline_reducer";
import CreateShopReducer from "../create_shop_reducer";
import GenerateSafetyAuditReducer from "../generate_safety_audit_reducer";
import InitUserReducer from "../init_user_reducer";
import InviteUserReducer from "../invite_user_reducer";
import LogSpillReducer from "../log_spill_reducer";
import UpdateQuantityReducer from "../update_quantity_reducer";
import UploadSdsReducer from "../upload_sds_reducer";

export type AcceptInviteParams = __Infer<typeof AcceptInviteReducer>;
export type AddInventoryItemParams = __Infer<typeof AddInventoryItemReducer>;
export type CreateDeadlineParams = __Infer<typeof CreateDeadlineReducer>;
export type CreateShopParams = __Infer<typeof CreateShopReducer>;
export type GenerateSafetyAuditParams = __Infer<typeof GenerateSafetyAuditReducer>;
export type InitUserParams = __Infer<typeof InitUserReducer>;
export type InviteUserParams = __Infer<typeof InviteUserReducer>;
export type LogSpillParams = __Infer<typeof LogSpillReducer>;
export type UpdateQuantityParams = __Infer<typeof UpdateQuantityReducer>;
export type UploadSdsParams = __Infer<typeof UploadSdsReducer>;

