// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u32().primaryKey(),
  shopId: __t.identity().name("shop_id"),
  chemicalId: __t.u32().name("chemical_id"),
  date: __t.timestamp(),
  amountSpilled: __t.f32().name("amount_spilled"),
  description: __t.string(),
  actionsTaken: __t.string().name("actions_taken"),
  witnesses: __t.string(),
});
